[project]
name = "anchain_aml_mcp"
version = "0.1.0"
description = "mcp server (stdio) for AnChain aml api"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.6",
    "requests>=2.32.4",
]

[project.scripts]
anchain_aml = "mcp_server:main"